kafka:
  adx:
    log:
      simple:
        servers: 172.29.1.210:9092,172.29.1.34:9092,172.29.1.177:9092
        defaultTopic: staging-adxEventTopic
      detail:
        servers: monetization-ad-log-kafka-01.meta.aws:9092,monetization-ad-log-kafka-02.meta.aws:9092,monetization-ad-log-kafka-03.meta.aws:9092,monetization-ad-log-kafka-04.meta.aws:9092,monetization-ad-log-kafka-05.meta.aws:9092
        defaultTopic: staging-adx-detail-log
#        172.29.1.42:9092,172.29.1.47:9092,172.29.1.31:9092,172.29.1.77:9092,172.29.1.119:9092
spring:
  datasource:
    url: jdbc:mysql://staging-new.copacaoqgakl.us-east-1.rds.amazonaws.com:3306/adx-new?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
    userName: apps_online
    password: GU^%^$%SKVR893k
    #    url: jdbc:mysql://localhost:3306/adx?createDatabaseIfNotExist=true
    #    userName: root
    #    password: ^usource
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    producer:

      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      acks: 1
    consumer:
      auto-commit-interval: 1S
      auto-offset-reset: earliest
      enable-auto-commit: true
      group-id: demo-vito-6
    #      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
#    listener:
#      concurrency: 2

#      ack-mode: manual_immediate
      missing-topics-fatal: false
#    bootstrap-servers: monetization-ad-log-kafka-01.meta.aws:9092,monetization-ad-log-kafka-02.meta.aws:9092,monetization-ad-log-kafka-03.meta.aws:9092,monetization-ad-log-kafka-04.meta.aws:9092,monetization-ad-log-kafka-05.meta.aws:9092
server:
  port: 8888
