spring:
  datasource:
    url: jdbc:mysql://staging-new.copacaoqgakl.us-east-1.rds.amazonaws.com:3306/adx-new?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
    userName: apps_online
    password: GU^%^$%SKVR893k
    #    url: jdbc:mysql://localhost:3306/adx?createDatabaseIfNotExist=true
    #    userName: root
    #    password: ^usource
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      acks: 1
    consumer:
      auto-commit-interval: 1S
      auto-offset-reset: latest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    listener:
      concurrency: 1

#      ack-mode: manual_immediate
      missing-topics-fatal: false
    bootstrap-servers: bigdata-realtime-stream-mobiukafka-new-01.meta.aws:9092,bigdata-realtime-stream-mobiukafka-new-02.meta.aws:9092,bigdata-realtime-stream-mobiukafka-new-03.meta.aws:9092,bigdata-realtime-stream-mobiukafka-new-04.meta.aws:9092,bigdata-realtime-stream-mobiukafka-new-05.meta.aws:9092,bigdata-realtime-stream-mobiukafka-new-06.meta.aws:9092,bigdata-realtime-stream-mobiukafka-new-07.meta.aws:9092
server:
  port: 8888
